// This file is generated by scripts/generate-modules.py.
// Do not edit manually.

export interface FlagIconDefinition {
  code: FlagIconCode;
  name: string;
  capital: string | null;
  continent: string | null;
  iso: boolean;
  square: string;
  rectangular: string;
}

export type FlagIconCode =
  | "af"
  | "ax"
  | "al"
  | "dz"
  | "as"
  | "ad"
  | "ao"
  | "ai"
  | "aq"
  | "ag"
  | "ar"
  | "am"
  | "aw"
  | "sh-ac"
  | "asean"
  | "au"
  | "at"
  | "az"
  | "bs"
  | "bh"
  | "bd"
  | "bb"
  | "es-pv"
  | "by"
  | "be"
  | "bz"
  | "bj"
  | "bm"
  | "bt"
  | "bo"
  | "bq"
  | "ba"
  | "bw"
  | "bv"
  | "br"
  | "io"
  | "bn"
  | "bg"
  | "bf"
  | "bi"
  | "cv"
  | "kh"
  | "cm"
  | "ca"
  | "ic"
  | "es-ct"
  | "ky"
  | "cf"
  | "cefta"
  | "td"
  | "cl"
  | "cn"
  | "cx"
  | "cp"
  | "cc"
  | "co"
  | "km"
  | "ck"
  | "cr"
  | "hr"
  | "cu"
  | "cw"
  | "cy"
  | "cz"
  | "ci"
  | "cd"
  | "dk"
  | "dg"
  | "dj"
  | "dm"
  | "do"
  | "eac"
  | "ec"
  | "eg"
  | "sv"
  | "gb-eng"
  | "gq"
  | "er"
  | "ee"
  | "sz"
  | "et"
  | "eu"
  | "fk"
  | "fo"
  | "fm"
  | "fj"
  | "fi"
  | "fr"
  | "gf"
  | "pf"
  | "tf"
  | "ga"
  | "es-ga"
  | "gm"
  | "ge"
  | "de"
  | "gh"
  | "gi"
  | "gr"
  | "gl"
  | "gd"
  | "gp"
  | "gu"
  | "gt"
  | "gg"
  | "gn"
  | "gw"
  | "gy"
  | "ht"
  | "hm"
  | "va"
  | "hn"
  | "hk"
  | "hu"
  | "is"
  | "in"
  | "id"
  | "ir"
  | "iq"
  | "ie"
  | "im"
  | "il"
  | "it"
  | "jm"
  | "jp"
  | "je"
  | "jo"
  | "kz"
  | "ke"
  | "ki"
  | "xk"
  | "kw"
  | "kg"
  | "la"
  | "lv"
  | "arab"
  | "lb"
  | "ls"
  | "lr"
  | "ly"
  | "li"
  | "lt"
  | "lu"
  | "mo"
  | "mg"
  | "mw"
  | "my"
  | "mv"
  | "ml"
  | "mt"
  | "mh"
  | "mq"
  | "mr"
  | "mu"
  | "yt"
  | "mx"
  | "md"
  | "mc"
  | "mn"
  | "me"
  | "ms"
  | "ma"
  | "mz"
  | "mm"
  | "na"
  | "nr"
  | "np"
  | "nl"
  | "nc"
  | "nz"
  | "ni"
  | "ne"
  | "ng"
  | "nu"
  | "nf"
  | "kp"
  | "mk"
  | "gb-nir"
  | "mp"
  | "no"
  | "om"
  | "pc"
  | "pk"
  | "pw"
  | "pa"
  | "pg"
  | "py"
  | "pe"
  | "ph"
  | "pn"
  | "pl"
  | "pt"
  | "pr"
  | "qa"
  | "cg"
  | "ro"
  | "ru"
  | "rw"
  | "re"
  | "bl"
  | "sh-hl"
  | "sh"
  | "kn"
  | "lc"
  | "mf"
  | "pm"
  | "vc"
  | "ws"
  | "sm"
  | "st"
  | "sa"
  | "gb-sct"
  | "sn"
  | "rs"
  | "sc"
  | "sl"
  | "sg"
  | "sx"
  | "sk"
  | "si"
  | "sb"
  | "so"
  | "za"
  | "gs"
  | "kr"
  | "ss"
  | "es"
  | "lk"
  | "ps"
  | "sd"
  | "sr"
  | "sj"
  | "se"
  | "ch"
  | "sy"
  | "tw"
  | "tj"
  | "tz"
  | "th"
  | "tl"
  | "tg"
  | "tk"
  | "to"
  | "tt"
  | "sh-ta"
  | "tn"
  | "tm"
  | "tc"
  | "tv"
  | "tr"
  | "ug"
  | "ua"
  | "ae"
  | "gb"
  | "un"
  | "um"
  | "us"
  | "xx"
  | "uy"
  | "uz"
  | "vu"
  | "ve"
  | "vn"
  | "vg"
  | "vi"
  | "gb-wls"
  | "wf"
  | "eh"
  | "ye"
  | "zm"
  | "zw";

export type FlagIcon = FlagIconDefinition;

export declare const flagAf: FlagIconDefinition;
export declare const flagAx: FlagIconDefinition;
export declare const flagAl: FlagIconDefinition;
export declare const flagDz: FlagIconDefinition;
export declare const flagAs: FlagIconDefinition;
export declare const flagAd: FlagIconDefinition;
export declare const flagAo: FlagIconDefinition;
export declare const flagAi: FlagIconDefinition;
export declare const flagAq: FlagIconDefinition;
export declare const flagAg: FlagIconDefinition;
export declare const flagAr: FlagIconDefinition;
export declare const flagAm: FlagIconDefinition;
export declare const flagAw: FlagIconDefinition;
export declare const flagShAc: FlagIconDefinition;
export declare const flagAsean: FlagIconDefinition;
export declare const flagAu: FlagIconDefinition;
export declare const flagAt: FlagIconDefinition;
export declare const flagAz: FlagIconDefinition;
export declare const flagBs: FlagIconDefinition;
export declare const flagBh: FlagIconDefinition;
export declare const flagBd: FlagIconDefinition;
export declare const flagBb: FlagIconDefinition;
export declare const flagEsPv: FlagIconDefinition;
export declare const flagBy: FlagIconDefinition;
export declare const flagBe: FlagIconDefinition;
export declare const flagBz: FlagIconDefinition;
export declare const flagBj: FlagIconDefinition;
export declare const flagBm: FlagIconDefinition;
export declare const flagBt: FlagIconDefinition;
export declare const flagBo: FlagIconDefinition;
export declare const flagBq: FlagIconDefinition;
export declare const flagBa: FlagIconDefinition;
export declare const flagBw: FlagIconDefinition;
export declare const flagBv: FlagIconDefinition;
export declare const flagBr: FlagIconDefinition;
export declare const flagIo: FlagIconDefinition;
export declare const flagBn: FlagIconDefinition;
export declare const flagBg: FlagIconDefinition;
export declare const flagBf: FlagIconDefinition;
export declare const flagBi: FlagIconDefinition;
export declare const flagCv: FlagIconDefinition;
export declare const flagKh: FlagIconDefinition;
export declare const flagCm: FlagIconDefinition;
export declare const flagCa: FlagIconDefinition;
export declare const flagIc: FlagIconDefinition;
export declare const flagEsCt: FlagIconDefinition;
export declare const flagKy: FlagIconDefinition;
export declare const flagCf: FlagIconDefinition;
export declare const flagCefta: FlagIconDefinition;
export declare const flagTd: FlagIconDefinition;
export declare const flagCl: FlagIconDefinition;
export declare const flagCn: FlagIconDefinition;
export declare const flagCx: FlagIconDefinition;
export declare const flagCp: FlagIconDefinition;
export declare const flagCc: FlagIconDefinition;
export declare const flagCo: FlagIconDefinition;
export declare const flagKm: FlagIconDefinition;
export declare const flagCk: FlagIconDefinition;
export declare const flagCr: FlagIconDefinition;
export declare const flagHr: FlagIconDefinition;
export declare const flagCu: FlagIconDefinition;
export declare const flagCw: FlagIconDefinition;
export declare const flagCy: FlagIconDefinition;
export declare const flagCz: FlagIconDefinition;
export declare const flagCi: FlagIconDefinition;
export declare const flagCd: FlagIconDefinition;
export declare const flagDk: FlagIconDefinition;
export declare const flagDg: FlagIconDefinition;
export declare const flagDj: FlagIconDefinition;
export declare const flagDm: FlagIconDefinition;
export declare const flagDo: FlagIconDefinition;
export declare const flagEac: FlagIconDefinition;
export declare const flagEc: FlagIconDefinition;
export declare const flagEg: FlagIconDefinition;
export declare const flagSv: FlagIconDefinition;
export declare const flagGbEng: FlagIconDefinition;
export declare const flagGq: FlagIconDefinition;
export declare const flagEr: FlagIconDefinition;
export declare const flagEe: FlagIconDefinition;
export declare const flagSz: FlagIconDefinition;
export declare const flagEt: FlagIconDefinition;
export declare const flagEu: FlagIconDefinition;
export declare const flagFk: FlagIconDefinition;
export declare const flagFo: FlagIconDefinition;
export declare const flagFm: FlagIconDefinition;
export declare const flagFj: FlagIconDefinition;
export declare const flagFi: FlagIconDefinition;
export declare const flagFr: FlagIconDefinition;
export declare const flagGf: FlagIconDefinition;
export declare const flagPf: FlagIconDefinition;
export declare const flagTf: FlagIconDefinition;
export declare const flagGa: FlagIconDefinition;
export declare const flagEsGa: FlagIconDefinition;
export declare const flagGm: FlagIconDefinition;
export declare const flagGe: FlagIconDefinition;
export declare const flagDe: FlagIconDefinition;
export declare const flagGh: FlagIconDefinition;
export declare const flagGi: FlagIconDefinition;
export declare const flagGr: FlagIconDefinition;
export declare const flagGl: FlagIconDefinition;
export declare const flagGd: FlagIconDefinition;
export declare const flagGp: FlagIconDefinition;
export declare const flagGu: FlagIconDefinition;
export declare const flagGt: FlagIconDefinition;
export declare const flagGg: FlagIconDefinition;
export declare const flagGn: FlagIconDefinition;
export declare const flagGw: FlagIconDefinition;
export declare const flagGy: FlagIconDefinition;
export declare const flagHt: FlagIconDefinition;
export declare const flagHm: FlagIconDefinition;
export declare const flagVa: FlagIconDefinition;
export declare const flagHn: FlagIconDefinition;
export declare const flagHk: FlagIconDefinition;
export declare const flagHu: FlagIconDefinition;
export declare const flagIs: FlagIconDefinition;
export declare const flagIn: FlagIconDefinition;
export declare const flagId: FlagIconDefinition;
export declare const flagIr: FlagIconDefinition;
export declare const flagIq: FlagIconDefinition;
export declare const flagIe: FlagIconDefinition;
export declare const flagIm: FlagIconDefinition;
export declare const flagIl: FlagIconDefinition;
export declare const flagIt: FlagIconDefinition;
export declare const flagJm: FlagIconDefinition;
export declare const flagJp: FlagIconDefinition;
export declare const flagJe: FlagIconDefinition;
export declare const flagJo: FlagIconDefinition;
export declare const flagKz: FlagIconDefinition;
export declare const flagKe: FlagIconDefinition;
export declare const flagKi: FlagIconDefinition;
export declare const flagXk: FlagIconDefinition;
export declare const flagKw: FlagIconDefinition;
export declare const flagKg: FlagIconDefinition;
export declare const flagLa: FlagIconDefinition;
export declare const flagLv: FlagIconDefinition;
export declare const flagArab: FlagIconDefinition;
export declare const flagLb: FlagIconDefinition;
export declare const flagLs: FlagIconDefinition;
export declare const flagLr: FlagIconDefinition;
export declare const flagLy: FlagIconDefinition;
export declare const flagLi: FlagIconDefinition;
export declare const flagLt: FlagIconDefinition;
export declare const flagLu: FlagIconDefinition;
export declare const flagMo: FlagIconDefinition;
export declare const flagMg: FlagIconDefinition;
export declare const flagMw: FlagIconDefinition;
export declare const flagMy: FlagIconDefinition;
export declare const flagMv: FlagIconDefinition;
export declare const flagMl: FlagIconDefinition;
export declare const flagMt: FlagIconDefinition;
export declare const flagMh: FlagIconDefinition;
export declare const flagMq: FlagIconDefinition;
export declare const flagMr: FlagIconDefinition;
export declare const flagMu: FlagIconDefinition;
export declare const flagYt: FlagIconDefinition;
export declare const flagMx: FlagIconDefinition;
export declare const flagMd: FlagIconDefinition;
export declare const flagMc: FlagIconDefinition;
export declare const flagMn: FlagIconDefinition;
export declare const flagMe: FlagIconDefinition;
export declare const flagMs: FlagIconDefinition;
export declare const flagMa: FlagIconDefinition;
export declare const flagMz: FlagIconDefinition;
export declare const flagMm: FlagIconDefinition;
export declare const flagNa: FlagIconDefinition;
export declare const flagNr: FlagIconDefinition;
export declare const flagNp: FlagIconDefinition;
export declare const flagNl: FlagIconDefinition;
export declare const flagNc: FlagIconDefinition;
export declare const flagNz: FlagIconDefinition;
export declare const flagNi: FlagIconDefinition;
export declare const flagNe: FlagIconDefinition;
export declare const flagNg: FlagIconDefinition;
export declare const flagNu: FlagIconDefinition;
export declare const flagNf: FlagIconDefinition;
export declare const flagKp: FlagIconDefinition;
export declare const flagMk: FlagIconDefinition;
export declare const flagGbNir: FlagIconDefinition;
export declare const flagMp: FlagIconDefinition;
export declare const flagNo: FlagIconDefinition;
export declare const flagOm: FlagIconDefinition;
export declare const flagPc: FlagIconDefinition;
export declare const flagPk: FlagIconDefinition;
export declare const flagPw: FlagIconDefinition;
export declare const flagPa: FlagIconDefinition;
export declare const flagPg: FlagIconDefinition;
export declare const flagPy: FlagIconDefinition;
export declare const flagPe: FlagIconDefinition;
export declare const flagPh: FlagIconDefinition;
export declare const flagPn: FlagIconDefinition;
export declare const flagPl: FlagIconDefinition;
export declare const flagPt: FlagIconDefinition;
export declare const flagPr: FlagIconDefinition;
export declare const flagQa: FlagIconDefinition;
export declare const flagCg: FlagIconDefinition;
export declare const flagRo: FlagIconDefinition;
export declare const flagRu: FlagIconDefinition;
export declare const flagRw: FlagIconDefinition;
export declare const flagRe: FlagIconDefinition;
export declare const flagBl: FlagIconDefinition;
export declare const flagShHl: FlagIconDefinition;
export declare const flagSh: FlagIconDefinition;
export declare const flagKn: FlagIconDefinition;
export declare const flagLc: FlagIconDefinition;
export declare const flagMf: FlagIconDefinition;
export declare const flagPm: FlagIconDefinition;
export declare const flagVc: FlagIconDefinition;
export declare const flagWs: FlagIconDefinition;
export declare const flagSm: FlagIconDefinition;
export declare const flagSt: FlagIconDefinition;
export declare const flagSa: FlagIconDefinition;
export declare const flagGbSct: FlagIconDefinition;
export declare const flagSn: FlagIconDefinition;
export declare const flagRs: FlagIconDefinition;
export declare const flagSc: FlagIconDefinition;
export declare const flagSl: FlagIconDefinition;
export declare const flagSg: FlagIconDefinition;
export declare const flagSx: FlagIconDefinition;
export declare const flagSk: FlagIconDefinition;
export declare const flagSi: FlagIconDefinition;
export declare const flagSb: FlagIconDefinition;
export declare const flagSo: FlagIconDefinition;
export declare const flagZa: FlagIconDefinition;
export declare const flagGs: FlagIconDefinition;
export declare const flagKr: FlagIconDefinition;
export declare const flagSs: FlagIconDefinition;
export declare const flagEs: FlagIconDefinition;
export declare const flagLk: FlagIconDefinition;
export declare const flagPs: FlagIconDefinition;
export declare const flagSd: FlagIconDefinition;
export declare const flagSr: FlagIconDefinition;
export declare const flagSj: FlagIconDefinition;
export declare const flagSe: FlagIconDefinition;
export declare const flagCh: FlagIconDefinition;
export declare const flagSy: FlagIconDefinition;
export declare const flagTw: FlagIconDefinition;
export declare const flagTj: FlagIconDefinition;
export declare const flagTz: FlagIconDefinition;
export declare const flagTh: FlagIconDefinition;
export declare const flagTl: FlagIconDefinition;
export declare const flagTg: FlagIconDefinition;
export declare const flagTk: FlagIconDefinition;
export declare const flagTo: FlagIconDefinition;
export declare const flagTt: FlagIconDefinition;
export declare const flagShTa: FlagIconDefinition;
export declare const flagTn: FlagIconDefinition;
export declare const flagTm: FlagIconDefinition;
export declare const flagTc: FlagIconDefinition;
export declare const flagTv: FlagIconDefinition;
export declare const flagTr: FlagIconDefinition;
export declare const flagUg: FlagIconDefinition;
export declare const flagUa: FlagIconDefinition;
export declare const flagAe: FlagIconDefinition;
export declare const flagGb: FlagIconDefinition;
export declare const flagUn: FlagIconDefinition;
export declare const flagUm: FlagIconDefinition;
export declare const flagUs: FlagIconDefinition;
export declare const flagXx: FlagIconDefinition;
export declare const flagUy: FlagIconDefinition;
export declare const flagUz: FlagIconDefinition;
export declare const flagVu: FlagIconDefinition;
export declare const flagVe: FlagIconDefinition;
export declare const flagVn: FlagIconDefinition;
export declare const flagVg: FlagIconDefinition;
export declare const flagVi: FlagIconDefinition;
export declare const flagGbWls: FlagIconDefinition;
export declare const flagWf: FlagIconDefinition;
export declare const flagEh: FlagIconDefinition;
export declare const flagYe: FlagIconDefinition;
export declare const flagZm: FlagIconDefinition;
export declare const flagZw: FlagIconDefinition;
