// This file is generated by scripts/generate-modules.py.
// Do not edit manually.

const createFlag = (code, name, capital, continent, iso) =>
  Object.freeze({
    code,
    name,
    capital,
    continent,
    iso,
    square: new URL(`../flags/1x1/${code}.svg`, import.meta.url).href,
    rectangular: new URL(`../flags/4x3/${code}.svg`, import.meta.url).href,
  });

export const flagAf = createFlag("af", "Afghanistan", "Kabul", "Asia", true);
export const flagAx = createFlag(
  "ax",
  "Aland Islands",
  "Mariehamn",
  "Europe",
  true,
);
export const flagAl = createFlag("al", "Albania", "Tirana", "Europe", true);
export const flagDz = createFlag("dz", "Algeria", "Algiers", "Africa", true);
export const flagAs = createFlag(
  "as",
  "American Samoa",
  "Pago Pago",
  "Oceania",
  true,
);
export const flagAd = createFlag(
  "ad",
  "Andorra",
  "Andorra la Vella",
  "Europe",
  true,
);
export const flagAo = createFlag("ao", "Angola", "Luanda", "Africa", true);
export const flagAi = createFlag(
  "ai",
  "Anguilla",
  "The Valley",
  "North America",
  true,
);
export const flagAq = createFlag("aq", "Antarctica", null, null, true);
export const flagAg = createFlag(
  "ag",
  "Antigua and Barbuda",
  "St. John's",
  "North America",
  true,
);
export const flagAr = createFlag(
  "ar",
  "Argentina",
  "Buenos Aires",
  "South America",
  true,
);
export const flagAm = createFlag("am", "Armenia", "Yerevan", "Asia", true);
export const flagAw = createFlag(
  "aw",
  "Aruba",
  "Oranjestad",
  "South America",
  true,
);
export const flagShAc = createFlag(
  "sh-ac",
  "Ascension Island",
  "Georgetown",
  "Africa",
  false,
);
export const flagAsean = createFlag(
  "asean",
  "Association of Southeast Asian Nations",
  null,
  null,
  false,
);
export const flagAu = createFlag(
  "au",
  "Australia",
  "Canberra",
  "Oceania",
  true,
);
export const flagAt = createFlag("at", "Austria", "Vienna", "Europe", true);
export const flagAz = createFlag("az", "Azerbaijan", "Baku", "Asia", true);
export const flagBs = createFlag(
  "bs",
  "Bahamas",
  "Nassau",
  "North America",
  true,
);
export const flagBh = createFlag("bh", "Bahrain", "Manama", "Asia", true);
export const flagBd = createFlag("bd", "Bangladesh", "Dhaka", "Asia", true);
export const flagBb = createFlag(
  "bb",
  "Barbados",
  "Bridgetown",
  "North America",
  true,
);
export const flagEsPv = createFlag(
  "es-pv",
  "Basque Country",
  null,
  null,
  false,
);
export const flagBy = createFlag("by", "Belarus", "Minsk", "Europe", true);
export const flagBe = createFlag("be", "Belgium", "Brussels", "Europe", true);
export const flagBz = createFlag(
  "bz",
  "Belize",
  "Belmopan",
  "North America",
  true,
);
export const flagBj = createFlag("bj", "Benin", "Porto-Novo", "Africa", true);
export const flagBm = createFlag(
  "bm",
  "Bermuda",
  "Hamilton",
  "North America",
  true,
);
export const flagBt = createFlag("bt", "Bhutan", "Thimphu", "Asia", true);
export const flagBo = createFlag(
  "bo",
  "Bolivia",
  "Sucre",
  "South America",
  true,
);
export const flagBq = createFlag(
  "bq",
  "Bonaire, Sint Eustatius and Saba",
  "Kralendijk",
  "South America",
  true,
);
export const flagBa = createFlag(
  "ba",
  "Bosnia and Herzegovina",
  "Sarajevo",
  "Europe",
  true,
);
export const flagBw = createFlag("bw", "Botswana", "Gaborone", "Africa", true);
export const flagBv = createFlag("bv", "Bouvet Island", null, null, true);
export const flagBr = createFlag(
  "br",
  "Brazil",
  "Brasília",
  "South America",
  true,
);
export const flagIo = createFlag(
  "io",
  "British Indian Ocean Territory",
  "Diego Garcia",
  "Asia",
  true,
);
export const flagBn = createFlag(
  "bn",
  "Brunei Darussalam",
  "Bandar Seri Begawan",
  "Asia",
  true,
);
export const flagBg = createFlag("bg", "Bulgaria", "Sofia", "Europe", true);
export const flagBf = createFlag(
  "bf",
  "Burkina Faso",
  "Ouagadougou",
  "Africa",
  true,
);
export const flagBi = createFlag("bi", "Burundi", "Bujumbura", "Africa", true);
export const flagCv = createFlag("cv", "Cabo Verde", "Praia", "Africa", true);
export const flagKh = createFlag("kh", "Cambodia", "Phnom Penh", "Asia", true);
export const flagCm = createFlag("cm", "Cameroon", "Yaoundé", "Africa", true);
export const flagCa = createFlag(
  "ca",
  "Canada",
  "Ottawa",
  "North America",
  true,
);
export const flagIc = createFlag("ic", "Canary Islands", null, null, false);
export const flagEsCt = createFlag("es-ct", "Catalonia", null, null, false);
export const flagKy = createFlag(
  "ky",
  "Cayman Islands",
  "George Town",
  "North America",
  true,
);
export const flagCf = createFlag(
  "cf",
  "Central African Republic",
  "Bangui",
  "Africa",
  true,
);
export const flagCefta = createFlag(
  "cefta",
  "Central European Free Trade Agreement",
  null,
  null,
  false,
);
export const flagTd = createFlag("td", "Chad", "N'Djamena", "Africa", true);
export const flagCl = createFlag(
  "cl",
  "Chile",
  "Santiago",
  "South America",
  true,
);
export const flagCn = createFlag("cn", "China", "Beijing", "Asia", true);
export const flagCx = createFlag(
  "cx",
  "Christmas Island",
  "Flying Fish Cove",
  "Asia",
  true,
);
export const flagCp = createFlag("cp", "Clipperton Island", null, null, false);
export const flagCc = createFlag(
  "cc",
  "Cocos (Keeling) Islands",
  "West Island",
  "Asia",
  true,
);
export const flagCo = createFlag(
  "co",
  "Colombia",
  "Bogotá",
  "South America",
  true,
);
export const flagKm = createFlag("km", "Comoros", "Moroni", "Africa", true);
export const flagCk = createFlag(
  "ck",
  "Cook Islands",
  "Avarua",
  "Oceania",
  true,
);
export const flagCr = createFlag(
  "cr",
  "Costa Rica",
  "San José",
  "North America",
  true,
);
export const flagHr = createFlag("hr", "Croatia", "Zagreb", "Europe", true);
export const flagCu = createFlag("cu", "Cuba", "Havana", "North America", true);
export const flagCw = createFlag(
  "cw",
  "Curaçao",
  "Willemstad",
  "South America",
  true,
);
export const flagCy = createFlag("cy", "Cyprus", "Nicosia", "Europe", true);
export const flagCz = createFlag(
  "cz",
  "Czech Republic",
  "Prague",
  "Europe",
  true,
);
export const flagCi = createFlag(
  "ci",
  "Côte d'Ivoire",
  "Yamoussoukro",
  "Africa",
  true,
);
export const flagCd = createFlag(
  "cd",
  "Democratic Republic of the Congo",
  "Kinshasa",
  "Africa",
  true,
);
export const flagDk = createFlag("dk", "Denmark", "Copenhagen", "Europe", true);
export const flagDg = createFlag("dg", "Diego Garcia", null, null, false);
export const flagDj = createFlag("dj", "Djibouti", "Djibouti", "Africa", true);
export const flagDm = createFlag(
  "dm",
  "Dominica",
  "Roseau",
  "North America",
  true,
);
export const flagDo = createFlag(
  "do",
  "Dominican Republic",
  "Santo Domingo",
  "North America",
  true,
);
export const flagEac = createFlag(
  "eac",
  "East African Community",
  null,
  null,
  false,
);
export const flagEc = createFlag(
  "ec",
  "Ecuador",
  "Quito",
  "South America",
  true,
);
export const flagEg = createFlag("eg", "Egypt", "Cairo", "Africa", true);
export const flagSv = createFlag(
  "sv",
  "El Salvador",
  "San Salvador",
  "North America",
  true,
);
export const flagGbEng = createFlag(
  "gb-eng",
  "England",
  "London",
  "Europe",
  false,
);
export const flagGq = createFlag(
  "gq",
  "Equatorial Guinea",
  "Malabo",
  "Africa",
  true,
);
export const flagEr = createFlag("er", "Eritrea", "Asmara", "Africa", true);
export const flagEe = createFlag("ee", "Estonia", "Tallinn", "Europe", true);
export const flagSz = createFlag(
  "sz",
  "Eswatini",
  "Lobamba, Mbabane",
  "Africa",
  true,
);
export const flagEt = createFlag(
  "et",
  "Ethiopia",
  "Addis Ababa",
  "Africa",
  true,
);
export const flagEu = createFlag("eu", "Europe", null, null, false);
export const flagFk = createFlag(
  "fk",
  "Falkland Islands",
  "Stanley",
  "South America",
  true,
);
export const flagFo = createFlag(
  "fo",
  "Faroe Islands",
  "Tórshavn",
  "Europe",
  true,
);
export const flagFm = createFlag(
  "fm",
  "Federated States of Micronesia",
  "Palikir",
  "Oceania",
  true,
);
export const flagFj = createFlag("fj", "Fiji", "Suva", "Oceania", true);
export const flagFi = createFlag("fi", "Finland", "Helsinki", "Europe", true);
export const flagFr = createFlag("fr", "France", "Paris", "Europe", true);
export const flagGf = createFlag(
  "gf",
  "French Guiana",
  "Cayenne",
  "South America",
  true,
);
export const flagPf = createFlag(
  "pf",
  "French Polynesia",
  "Papeete",
  "Oceania",
  true,
);
export const flagTf = createFlag(
  "tf",
  "French Southern Territories",
  "Saint-Pierre, Réunion",
  "Africa",
  true,
);
export const flagGa = createFlag("ga", "Gabon", "Libreville", "Africa", true);
export const flagEsGa = createFlag("es-ga", "Galicia", null, null, false);
export const flagGm = createFlag("gm", "Gambia", "Banjul", "Africa", true);
export const flagGe = createFlag("ge", "Georgia", "Tbilisi", "Asia", true);
export const flagDe = createFlag("de", "Germany", "Berlin", "Europe", true);
export const flagGh = createFlag("gh", "Ghana", "Accra", "Africa", true);
export const flagGi = createFlag(
  "gi",
  "Gibraltar",
  "Gibraltar",
  "Europe",
  true,
);
export const flagGr = createFlag("gr", "Greece", "Athens", "Europe", true);
export const flagGl = createFlag(
  "gl",
  "Greenland",
  "Nuuk",
  "North America",
  true,
);
export const flagGd = createFlag(
  "gd",
  "Grenada",
  "St. George's",
  "North America",
  true,
);
export const flagGp = createFlag(
  "gp",
  "Guadeloupe",
  "Basse-Terre",
  "North America",
  true,
);
export const flagGu = createFlag("gu", "Guam", "Hagåtña", "Oceania", true);
export const flagGt = createFlag(
  "gt",
  "Guatemala",
  "Guatemala City",
  "North America",
  true,
);
export const flagGg = createFlag(
  "gg",
  "Guernsey",
  "Saint Peter Port",
  "Europe",
  true,
);
export const flagGn = createFlag("gn", "Guinea", "Conakry", "Africa", true);
export const flagGw = createFlag(
  "gw",
  "Guinea-Bissau",
  "Bissau",
  "Africa",
  true,
);
export const flagGy = createFlag(
  "gy",
  "Guyana",
  "Georgetown",
  "South America",
  true,
);
export const flagHt = createFlag(
  "ht",
  "Haiti",
  "Port-au-Prince",
  "North America",
  true,
);
export const flagHm = createFlag(
  "hm",
  "Heard Island and McDonald Islands",
  null,
  null,
  true,
);
export const flagVa = createFlag(
  "va",
  "Holy See",
  "Vatican City",
  "Europe",
  true,
);
export const flagHn = createFlag(
  "hn",
  "Honduras",
  "Tegucigalpa",
  "North America",
  true,
);
export const flagHk = createFlag("hk", "Hong Kong", "Hong Kong", "Asia", true);
export const flagHu = createFlag("hu", "Hungary", "Budapest", "Europe", true);
export const flagIs = createFlag("is", "Iceland", "Reykjavik", "Europe", true);
export const flagIn = createFlag("in", "India", "New Delhi", "Asia", true);
export const flagId = createFlag("id", "Indonesia", "Jakarta", "Asia", true);
export const flagIr = createFlag("ir", "Iran", "Tehran", "Asia", true);
export const flagIq = createFlag("iq", "Iraq", "Baghdad", "Asia", true);
export const flagIe = createFlag("ie", "Ireland", "Dublin", "Europe", true);
export const flagIm = createFlag(
  "im",
  "Isle of Man",
  "Douglas",
  "Europe",
  true,
);
export const flagIl = createFlag("il", "Israel", "Jerusalem", "Asia", true);
export const flagIt = createFlag("it", "Italy", "Rome", "Europe", true);
export const flagJm = createFlag(
  "jm",
  "Jamaica",
  "Kingston",
  "North America",
  true,
);
export const flagJp = createFlag("jp", "Japan", "Tokyo", "Asia", true);
export const flagJe = createFlag(
  "je",
  "Jersey",
  "Saint Helier",
  "Europe",
  true,
);
export const flagJo = createFlag("jo", "Jordan", "Amman", "Asia", true);
export const flagKz = createFlag("kz", "Kazakhstan", "Astana", "Asia", true);
export const flagKe = createFlag("ke", "Kenya", "Nairobi", "Africa", true);
export const flagKi = createFlag(
  "ki",
  "Kiribati",
  "South Tarawa",
  "Oceania",
  true,
);
export const flagXk = createFlag("xk", "Kosovo", "Pristina", "Europe", false);
export const flagKw = createFlag("kw", "Kuwait", "Kuwait City", "Asia", true);
export const flagKg = createFlag("kg", "Kyrgyzstan", "Bishkek", "Asia", true);
export const flagLa = createFlag("la", "Laos", "Vientiane", "Asia", true);
export const flagLv = createFlag("lv", "Latvia", "Riga", "Europe", true);
export const flagArab = createFlag(
  "arab",
  "League of Arab States",
  null,
  null,
  false,
);
export const flagLb = createFlag("lb", "Lebanon", "Beirut", "Asia", true);
export const flagLs = createFlag("ls", "Lesotho", "Maseru", "Africa", true);
export const flagLr = createFlag("lr", "Liberia", "Monrovia", "Africa", true);
export const flagLy = createFlag("ly", "Libya", "Tripoli", "Africa", true);
export const flagLi = createFlag(
  "li",
  "Liechtenstein",
  "Vaduz",
  "Europe",
  true,
);
export const flagLt = createFlag("lt", "Lithuania", "Vilnius", "Europe", true);
export const flagLu = createFlag(
  "lu",
  "Luxembourg",
  "Luxembourg City",
  "Europe",
  true,
);
export const flagMo = createFlag("mo", "Macau", "Macau", "Asia", true);
export const flagMg = createFlag(
  "mg",
  "Madagascar",
  "Antananarivo",
  "Africa",
  true,
);
export const flagMw = createFlag("mw", "Malawi", "Lilongwe", "Africa", true);
export const flagMy = createFlag(
  "my",
  "Malaysia",
  "Kuala Lumpur",
  "Asia",
  true,
);
export const flagMv = createFlag("mv", "Maldives", "Malé", "Asia", true);
export const flagMl = createFlag("ml", "Mali", "Bamako", "Africa", true);
export const flagMt = createFlag("mt", "Malta", "Valletta", "Europe", true);
export const flagMh = createFlag(
  "mh",
  "Marshall Islands",
  "Majuro",
  "Oceania",
  true,
);
export const flagMq = createFlag(
  "mq",
  "Martinique",
  "Fort-de-France",
  "North America",
  true,
);
export const flagMr = createFlag(
  "mr",
  "Mauritania",
  "Nouakchott",
  "Africa",
  true,
);
export const flagMu = createFlag(
  "mu",
  "Mauritius",
  "Port Louis",
  "Africa",
  true,
);
export const flagYt = createFlag("yt", "Mayotte", "Mamoudzou", "Africa", true);
export const flagMx = createFlag(
  "mx",
  "Mexico",
  "Mexico City",
  "North America",
  true,
);
export const flagMd = createFlag("md", "Moldova", "Chișinău", "Europe", true);
export const flagMc = createFlag("mc", "Monaco", "Monaco", "Europe", true);
export const flagMn = createFlag("mn", "Mongolia", "Ulaanbaatar", "Asia", true);
export const flagMe = createFlag(
  "me",
  "Montenegro",
  "Podgorica",
  "Europe",
  true,
);
export const flagMs = createFlag(
  "ms",
  "Montserrat",
  "Little Bay, Brades, Plymouth",
  "North America",
  true,
);
export const flagMa = createFlag("ma", "Morocco", "Rabat", "Africa", true);
export const flagMz = createFlag("mz", "Mozambique", "Maputo", "Africa", true);
export const flagMm = createFlag("mm", "Myanmar", "Naypyidaw", "Asia", true);
export const flagNa = createFlag("na", "Namibia", "Windhoek", "Africa", true);
export const flagNr = createFlag(
  "nr",
  "Nauru",
  "Yaren District",
  "Oceania",
  true,
);
export const flagNp = createFlag("np", "Nepal", "Kathmandu", "Asia", true);
export const flagNl = createFlag(
  "nl",
  "Netherlands",
  "Amsterdam",
  "Europe",
  true,
);
export const flagNc = createFlag(
  "nc",
  "New Caledonia",
  "Nouméa",
  "Oceania",
  true,
);
export const flagNz = createFlag(
  "nz",
  "New Zealand",
  "Wellington",
  "Oceania",
  true,
);
export const flagNi = createFlag(
  "ni",
  "Nicaragua",
  "Managua",
  "North America",
  true,
);
export const flagNe = createFlag("ne", "Niger", "Niamey", "Africa", true);
export const flagNg = createFlag("ng", "Nigeria", "Abuja", "Africa", true);
export const flagNu = createFlag("nu", "Niue", "Alofi", "Oceania", true);
export const flagNf = createFlag(
  "nf",
  "Norfolk Island",
  "Kingston",
  "Oceania",
  true,
);
export const flagKp = createFlag(
  "kp",
  "North Korea",
  "Pyongyang",
  "Asia",
  true,
);
export const flagMk = createFlag(
  "mk",
  "North Macedonia",
  "Skopje",
  "Europe",
  true,
);
export const flagGbNir = createFlag(
  "gb-nir",
  "Northern Ireland",
  "Belfast",
  "Europe",
  false,
);
export const flagMp = createFlag(
  "mp",
  "Northern Mariana Islands",
  "Saipan",
  "Oceania",
  true,
);
export const flagNo = createFlag("no", "Norway", "Oslo", "Europe", true);
export const flagOm = createFlag("om", "Oman", "Muscat", "Asia", true);
export const flagPc = createFlag("pc", "Pacific Community", null, null, false);
export const flagPk = createFlag("pk", "Pakistan", "Islamabad", "Asia", true);
export const flagPw = createFlag("pw", "Palau", "Ngerulmud", "Oceania", true);
export const flagPa = createFlag(
  "pa",
  "Panama",
  "Panama City",
  "North America",
  true,
);
export const flagPg = createFlag(
  "pg",
  "Papua New Guinea",
  "Port Moresby",
  "Oceania",
  true,
);
export const flagPy = createFlag(
  "py",
  "Paraguay",
  "Asunción",
  "South America",
  true,
);
export const flagPe = createFlag("pe", "Peru", "Lima", "South America", true);
export const flagPh = createFlag("ph", "Philippines", "Manila", "Asia", true);
export const flagPn = createFlag(
  "pn",
  "Pitcairn",
  "Adamstown",
  "Oceania",
  true,
);
export const flagPl = createFlag("pl", "Poland", "Warsaw", "Europe", true);
export const flagPt = createFlag("pt", "Portugal", "Lisbon", "Europe", true);
export const flagPr = createFlag(
  "pr",
  "Puerto Rico",
  "San Juan",
  "North America",
  true,
);
export const flagQa = createFlag("qa", "Qatar", "Doha", "Asia", true);
export const flagCg = createFlag(
  "cg",
  "Republic of the Congo",
  "Brazzaville",
  "Africa",
  true,
);
export const flagRo = createFlag("ro", "Romania", "Bucharest", "Europe", true);
export const flagRu = createFlag("ru", "Russia", "Moscow", "Europe", true);
export const flagRw = createFlag("rw", "Rwanda", "Kigali", "Africa", true);
export const flagRe = createFlag(
  "re",
  "Réunion",
  "Saint-Denis",
  "Africa",
  true,
);
export const flagBl = createFlag(
  "bl",
  "Saint Barthélemy",
  "Gustavia",
  "North America",
  true,
);
export const flagShHl = createFlag(
  "sh-hl",
  "Saint Helena",
  "Jamestown",
  "Africa",
  false,
);
export const flagSh = createFlag(
  "sh",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Jamestown",
  "Africa",
  true,
);
export const flagKn = createFlag(
  "kn",
  "Saint Kitts and Nevis",
  "Basseterre",
  "North America",
  true,
);
export const flagLc = createFlag(
  "lc",
  "Saint Lucia",
  "Castries",
  "North America",
  true,
);
export const flagMf = createFlag(
  "mf",
  "Saint Martin",
  "Marigot",
  "North America",
  true,
);
export const flagPm = createFlag(
  "pm",
  "Saint Pierre and Miquelon",
  "Saint-Pierre",
  "North America",
  true,
);
export const flagVc = createFlag(
  "vc",
  "Saint Vincent and the Grenadines",
  "Kingstown",
  "North America",
  true,
);
export const flagWs = createFlag("ws", "Samoa", "Apia", "Oceania", true);
export const flagSm = createFlag(
  "sm",
  "San Marino",
  "San Marino",
  "Europe",
  true,
);
export const flagSt = createFlag(
  "st",
  "Sao Tome and Principe",
  "São Tomé",
  "Africa",
  true,
);
export const flagSa = createFlag("sa", "Saudi Arabia", "Riyadh", "Asia", true);
export const flagGbSct = createFlag(
  "gb-sct",
  "Scotland",
  "Edinburgh",
  "Europe",
  false,
);
export const flagSn = createFlag("sn", "Senegal", "Dakar", "Africa", true);
export const flagRs = createFlag("rs", "Serbia", "Belgrade", "Europe", true);
export const flagSc = createFlag(
  "sc",
  "Seychelles",
  "Victoria",
  "Africa",
  true,
);
export const flagSl = createFlag(
  "sl",
  "Sierra Leone",
  "Freetown",
  "Africa",
  true,
);
export const flagSg = createFlag("sg", "Singapore", "Singapore", "Asia", true);
export const flagSx = createFlag(
  "sx",
  "Sint Maarten",
  "Philipsburg",
  "North America",
  true,
);
export const flagSk = createFlag(
  "sk",
  "Slovakia",
  "Bratislava",
  "Europe",
  true,
);
export const flagSi = createFlag("si", "Slovenia", "Ljubljana", "Europe", true);
export const flagSb = createFlag(
  "sb",
  "Solomon Islands",
  "Honiara",
  "Oceania",
  true,
);
export const flagSo = createFlag("so", "Somalia", "Mogadishu", "Africa", true);
export const flagZa = createFlag(
  "za",
  "South Africa",
  "Pretoria",
  "Africa",
  true,
);
export const flagGs = createFlag(
  "gs",
  "South Georgia and the South Sandwich Islands",
  "King Edward Point",
  "Antarctica",
  true,
);
export const flagKr = createFlag("kr", "South Korea", "Seoul", "Asia", true);
export const flagSs = createFlag("ss", "South Sudan", "Juba", "Africa", true);
export const flagEs = createFlag("es", "Spain", "Madrid", "Europe", true);
export const flagLk = createFlag(
  "lk",
  "Sri Lanka",
  "Sri Jayawardenepura Kotte, Colombo",
  "Asia",
  true,
);
export const flagPs = createFlag(
  "ps",
  "State of Palestine",
  "Ramallah",
  "Asia",
  true,
);
export const flagSd = createFlag("sd", "Sudan", "Khartoum", "Africa", true);
export const flagSr = createFlag(
  "sr",
  "Suriname",
  "Paramaribo",
  "South America",
  true,
);
export const flagSj = createFlag(
  "sj",
  "Svalbard and Jan Mayen",
  "Longyearbyen",
  "Europe",
  true,
);
export const flagSe = createFlag("se", "Sweden", "Stockholm", "Europe", true);
export const flagCh = createFlag("ch", "Switzerland", "Bern", "Europe", true);
export const flagSy = createFlag("sy", "Syria", "Damascus", "Asia", true);
export const flagTw = createFlag("tw", "Taiwan", "Taipei", "Asia", true);
export const flagTj = createFlag("tj", "Tajikistan", "Dushanbe", "Asia", true);
export const flagTz = createFlag("tz", "Tanzania", "Dodoma", "Africa", true);
export const flagTh = createFlag("th", "Thailand", "Bangkok", "Asia", true);
export const flagTl = createFlag("tl", "Timor-Leste", "Dili", "Asia", true);
export const flagTg = createFlag("tg", "Togo", "Lomé", "Africa", true);
export const flagTk = createFlag(
  "tk",
  "Tokelau",
  "Nukunonu, Atafu,Tokelau",
  "Oceania",
  true,
);
export const flagTo = createFlag("to", "Tonga", "Nukuʻalofa", "Oceania", true);
export const flagTt = createFlag(
  "tt",
  "Trinidad and Tobago",
  "Port of Spain",
  "South America",
  true,
);
export const flagShTa = createFlag(
  "sh-ta",
  "Tristan da Cunha",
  "Edinburgh of the Seven Seas",
  "Africa",
  false,
);
export const flagTn = createFlag("tn", "Tunisia", "Tunis", "Africa", true);
export const flagTm = createFlag(
  "tm",
  "Turkmenistan",
  "Ashgabat",
  "Asia",
  true,
);
export const flagTc = createFlag(
  "tc",
  "Turks and Caicos Islands",
  "Cockburn Town",
  "North America",
  true,
);
export const flagTv = createFlag("tv", "Tuvalu", "Funafuti", "Oceania", true);
export const flagTr = createFlag("tr", "Türkiye", "Ankara", "Asia", true);
export const flagUg = createFlag("ug", "Uganda", "Kampala", "Africa", true);
export const flagUa = createFlag("ua", "Ukraine", "Kiev", "Europe", true);
export const flagAe = createFlag(
  "ae",
  "United Arab Emirates",
  "Abu Dhabi",
  "Asia",
  true,
);
export const flagGb = createFlag(
  "gb",
  "United Kingdom",
  "London",
  "Europe",
  true,
);
export const flagUn = createFlag("un", "United Nations", null, null, false);
export const flagUm = createFlag(
  "um",
  "United States Minor Outlying Islands",
  "Washington, D.C.",
  "North America",
  true,
);
export const flagUs = createFlag(
  "us",
  "United States of America",
  "Washington, D.C.",
  "North America",
  true,
);
export const flagXx = createFlag("xx", "Unknown", null, null, false);
export const flagUy = createFlag(
  "uy",
  "Uruguay",
  "Montevideo",
  "South America",
  true,
);
export const flagUz = createFlag("uz", "Uzbekistan", "Tashkent", "Asia", true);
export const flagVu = createFlag("vu", "Vanuatu", "Port Vila", "Oceania", true);
export const flagVe = createFlag(
  "ve",
  "Venezuela",
  "Caracas",
  "South America",
  true,
);
export const flagVn = createFlag("vn", "Vietnam", "Hanoi", "Asia", true);
export const flagVg = createFlag(
  "vg",
  "Virgin Islands (British)",
  "Road Town",
  "North America",
  true,
);
export const flagVi = createFlag(
  "vi",
  "Virgin Islands (U.S.)",
  "Charlotte Amalie",
  "North America",
  true,
);
export const flagGbWls = createFlag(
  "gb-wls",
  "Wales",
  "Cardiff",
  "Europe",
  false,
);
export const flagWf = createFlag(
  "wf",
  "Wallis and Futuna",
  "Mata-Utu",
  "Oceania",
  true,
);
export const flagEh = createFlag(
  "eh",
  "Western Sahara",
  "Laayoune",
  "Africa",
  true,
);
export const flagYe = createFlag("ye", "Yemen", "Sana'a", "Asia", true);
export const flagZm = createFlag("zm", "Zambia", "Lusaka", "Africa", true);
export const flagZw = createFlag("zw", "Zimbabwe", "Harare", "Africa", true);
