// This file is generated by scripts/generate-modules.py.
// Do not edit manually.
"use strict";

const path = require("path");

const createFlag = (code, name, capital, continent, iso) =>
  Object.freeze({
    code,
    name,
    capital,
    continent,
    iso,
    square: path.join(__dirname, "..", "flags", "1x1", `${code}.svg`),
    rectangular: path.join(__dirname, "..", "flags", "4x3", `${code}.svg`),
  });

const flagAf = createFlag("af", "Afghanistan", "Kabul", "Asia", true);
exports.flagAf = flagAf;

const flagAx = createFlag("ax", "Aland Islands", "Mariehamn", "Europe", true);
exports.flagAx = flagAx;

const flagAl = createFlag("al", "Albania", "Tirana", "Europe", true);
exports.flagAl = flagAl;

const flagDz = createFlag("dz", "Algeria", "Algiers", "Africa", true);
exports.flagDz = flagDz;

const flagAs = createFlag("as", "American Samoa", "Pago Pago", "Oceania", true);
exports.flagAs = flagAs;

const flagAd = createFlag("ad", "Andorra", "Andorra la Vella", "Europe", true);
exports.flagAd = flagAd;

const flagAo = createFlag("ao", "Angola", "Luanda", "Africa", true);
exports.flagAo = flagAo;

const flagAi = createFlag(
  "ai",
  "Anguilla",
  "The Valley",
  "North America",
  true,
);
exports.flagAi = flagAi;

const flagAq = createFlag("aq", "Antarctica", null, null, true);
exports.flagAq = flagAq;

const flagAg = createFlag(
  "ag",
  "Antigua and Barbuda",
  "St. John's",
  "North America",
  true,
);
exports.flagAg = flagAg;

const flagAr = createFlag(
  "ar",
  "Argentina",
  "Buenos Aires",
  "South America",
  true,
);
exports.flagAr = flagAr;

const flagAm = createFlag("am", "Armenia", "Yerevan", "Asia", true);
exports.flagAm = flagAm;

const flagAw = createFlag("aw", "Aruba", "Oranjestad", "South America", true);
exports.flagAw = flagAw;

const flagShAc = createFlag(
  "sh-ac",
  "Ascension Island",
  "Georgetown",
  "Africa",
  false,
);
exports.flagShAc = flagShAc;

const flagAsean = createFlag(
  "asean",
  "Association of Southeast Asian Nations",
  null,
  null,
  false,
);
exports.flagAsean = flagAsean;

const flagAu = createFlag("au", "Australia", "Canberra", "Oceania", true);
exports.flagAu = flagAu;

const flagAt = createFlag("at", "Austria", "Vienna", "Europe", true);
exports.flagAt = flagAt;

const flagAz = createFlag("az", "Azerbaijan", "Baku", "Asia", true);
exports.flagAz = flagAz;

const flagBs = createFlag("bs", "Bahamas", "Nassau", "North America", true);
exports.flagBs = flagBs;

const flagBh = createFlag("bh", "Bahrain", "Manama", "Asia", true);
exports.flagBh = flagBh;

const flagBd = createFlag("bd", "Bangladesh", "Dhaka", "Asia", true);
exports.flagBd = flagBd;

const flagBb = createFlag(
  "bb",
  "Barbados",
  "Bridgetown",
  "North America",
  true,
);
exports.flagBb = flagBb;

const flagEsPv = createFlag("es-pv", "Basque Country", null, null, false);
exports.flagEsPv = flagEsPv;

const flagBy = createFlag("by", "Belarus", "Minsk", "Europe", true);
exports.flagBy = flagBy;

const flagBe = createFlag("be", "Belgium", "Brussels", "Europe", true);
exports.flagBe = flagBe;

const flagBz = createFlag("bz", "Belize", "Belmopan", "North America", true);
exports.flagBz = flagBz;

const flagBj = createFlag("bj", "Benin", "Porto-Novo", "Africa", true);
exports.flagBj = flagBj;

const flagBm = createFlag("bm", "Bermuda", "Hamilton", "North America", true);
exports.flagBm = flagBm;

const flagBt = createFlag("bt", "Bhutan", "Thimphu", "Asia", true);
exports.flagBt = flagBt;

const flagBo = createFlag("bo", "Bolivia", "Sucre", "South America", true);
exports.flagBo = flagBo;

const flagBq = createFlag(
  "bq",
  "Bonaire, Sint Eustatius and Saba",
  "Kralendijk",
  "South America",
  true,
);
exports.flagBq = flagBq;

const flagBa = createFlag(
  "ba",
  "Bosnia and Herzegovina",
  "Sarajevo",
  "Europe",
  true,
);
exports.flagBa = flagBa;

const flagBw = createFlag("bw", "Botswana", "Gaborone", "Africa", true);
exports.flagBw = flagBw;

const flagBv = createFlag("bv", "Bouvet Island", null, null, true);
exports.flagBv = flagBv;

const flagBr = createFlag("br", "Brazil", "Brasília", "South America", true);
exports.flagBr = flagBr;

const flagIo = createFlag(
  "io",
  "British Indian Ocean Territory",
  "Diego Garcia",
  "Asia",
  true,
);
exports.flagIo = flagIo;

const flagBn = createFlag(
  "bn",
  "Brunei Darussalam",
  "Bandar Seri Begawan",
  "Asia",
  true,
);
exports.flagBn = flagBn;

const flagBg = createFlag("bg", "Bulgaria", "Sofia", "Europe", true);
exports.flagBg = flagBg;

const flagBf = createFlag("bf", "Burkina Faso", "Ouagadougou", "Africa", true);
exports.flagBf = flagBf;

const flagBi = createFlag("bi", "Burundi", "Bujumbura", "Africa", true);
exports.flagBi = flagBi;

const flagCv = createFlag("cv", "Cabo Verde", "Praia", "Africa", true);
exports.flagCv = flagCv;

const flagKh = createFlag("kh", "Cambodia", "Phnom Penh", "Asia", true);
exports.flagKh = flagKh;

const flagCm = createFlag("cm", "Cameroon", "Yaoundé", "Africa", true);
exports.flagCm = flagCm;

const flagCa = createFlag("ca", "Canada", "Ottawa", "North America", true);
exports.flagCa = flagCa;

const flagIc = createFlag("ic", "Canary Islands", null, null, false);
exports.flagIc = flagIc;

const flagEsCt = createFlag("es-ct", "Catalonia", null, null, false);
exports.flagEsCt = flagEsCt;

const flagKy = createFlag(
  "ky",
  "Cayman Islands",
  "George Town",
  "North America",
  true,
);
exports.flagKy = flagKy;

const flagCf = createFlag(
  "cf",
  "Central African Republic",
  "Bangui",
  "Africa",
  true,
);
exports.flagCf = flagCf;

const flagCefta = createFlag(
  "cefta",
  "Central European Free Trade Agreement",
  null,
  null,
  false,
);
exports.flagCefta = flagCefta;

const flagTd = createFlag("td", "Chad", "N'Djamena", "Africa", true);
exports.flagTd = flagTd;

const flagCl = createFlag("cl", "Chile", "Santiago", "South America", true);
exports.flagCl = flagCl;

const flagCn = createFlag("cn", "China", "Beijing", "Asia", true);
exports.flagCn = flagCn;

const flagCx = createFlag(
  "cx",
  "Christmas Island",
  "Flying Fish Cove",
  "Asia",
  true,
);
exports.flagCx = flagCx;

const flagCp = createFlag("cp", "Clipperton Island", null, null, false);
exports.flagCp = flagCp;

const flagCc = createFlag(
  "cc",
  "Cocos (Keeling) Islands",
  "West Island",
  "Asia",
  true,
);
exports.flagCc = flagCc;

const flagCo = createFlag("co", "Colombia", "Bogotá", "South America", true);
exports.flagCo = flagCo;

const flagKm = createFlag("km", "Comoros", "Moroni", "Africa", true);
exports.flagKm = flagKm;

const flagCk = createFlag("ck", "Cook Islands", "Avarua", "Oceania", true);
exports.flagCk = flagCk;

const flagCr = createFlag(
  "cr",
  "Costa Rica",
  "San José",
  "North America",
  true,
);
exports.flagCr = flagCr;

const flagHr = createFlag("hr", "Croatia", "Zagreb", "Europe", true);
exports.flagHr = flagHr;

const flagCu = createFlag("cu", "Cuba", "Havana", "North America", true);
exports.flagCu = flagCu;

const flagCw = createFlag("cw", "Curaçao", "Willemstad", "South America", true);
exports.flagCw = flagCw;

const flagCy = createFlag("cy", "Cyprus", "Nicosia", "Europe", true);
exports.flagCy = flagCy;

const flagCz = createFlag("cz", "Czech Republic", "Prague", "Europe", true);
exports.flagCz = flagCz;

const flagCi = createFlag(
  "ci",
  "Côte d'Ivoire",
  "Yamoussoukro",
  "Africa",
  true,
);
exports.flagCi = flagCi;

const flagCd = createFlag(
  "cd",
  "Democratic Republic of the Congo",
  "Kinshasa",
  "Africa",
  true,
);
exports.flagCd = flagCd;

const flagDk = createFlag("dk", "Denmark", "Copenhagen", "Europe", true);
exports.flagDk = flagDk;

const flagDg = createFlag("dg", "Diego Garcia", null, null, false);
exports.flagDg = flagDg;

const flagDj = createFlag("dj", "Djibouti", "Djibouti", "Africa", true);
exports.flagDj = flagDj;

const flagDm = createFlag("dm", "Dominica", "Roseau", "North America", true);
exports.flagDm = flagDm;

const flagDo = createFlag(
  "do",
  "Dominican Republic",
  "Santo Domingo",
  "North America",
  true,
);
exports.flagDo = flagDo;

const flagEac = createFlag("eac", "East African Community", null, null, false);
exports.flagEac = flagEac;

const flagEc = createFlag("ec", "Ecuador", "Quito", "South America", true);
exports.flagEc = flagEc;

const flagEg = createFlag("eg", "Egypt", "Cairo", "Africa", true);
exports.flagEg = flagEg;

const flagSv = createFlag(
  "sv",
  "El Salvador",
  "San Salvador",
  "North America",
  true,
);
exports.flagSv = flagSv;

const flagGbEng = createFlag("gb-eng", "England", "London", "Europe", false);
exports.flagGbEng = flagGbEng;

const flagGq = createFlag("gq", "Equatorial Guinea", "Malabo", "Africa", true);
exports.flagGq = flagGq;

const flagEr = createFlag("er", "Eritrea", "Asmara", "Africa", true);
exports.flagEr = flagEr;

const flagEe = createFlag("ee", "Estonia", "Tallinn", "Europe", true);
exports.flagEe = flagEe;

const flagSz = createFlag("sz", "Eswatini", "Lobamba, Mbabane", "Africa", true);
exports.flagSz = flagSz;

const flagEt = createFlag("et", "Ethiopia", "Addis Ababa", "Africa", true);
exports.flagEt = flagEt;

const flagEu = createFlag("eu", "Europe", null, null, false);
exports.flagEu = flagEu;

const flagFk = createFlag(
  "fk",
  "Falkland Islands",
  "Stanley",
  "South America",
  true,
);
exports.flagFk = flagFk;

const flagFo = createFlag("fo", "Faroe Islands", "Tórshavn", "Europe", true);
exports.flagFo = flagFo;

const flagFm = createFlag(
  "fm",
  "Federated States of Micronesia",
  "Palikir",
  "Oceania",
  true,
);
exports.flagFm = flagFm;

const flagFj = createFlag("fj", "Fiji", "Suva", "Oceania", true);
exports.flagFj = flagFj;

const flagFi = createFlag("fi", "Finland", "Helsinki", "Europe", true);
exports.flagFi = flagFi;

const flagFr = createFlag("fr", "France", "Paris", "Europe", true);
exports.flagFr = flagFr;

const flagGf = createFlag(
  "gf",
  "French Guiana",
  "Cayenne",
  "South America",
  true,
);
exports.flagGf = flagGf;

const flagPf = createFlag("pf", "French Polynesia", "Papeete", "Oceania", true);
exports.flagPf = flagPf;

const flagTf = createFlag(
  "tf",
  "French Southern Territories",
  "Saint-Pierre, Réunion",
  "Africa",
  true,
);
exports.flagTf = flagTf;

const flagGa = createFlag("ga", "Gabon", "Libreville", "Africa", true);
exports.flagGa = flagGa;

const flagEsGa = createFlag("es-ga", "Galicia", null, null, false);
exports.flagEsGa = flagEsGa;

const flagGm = createFlag("gm", "Gambia", "Banjul", "Africa", true);
exports.flagGm = flagGm;

const flagGe = createFlag("ge", "Georgia", "Tbilisi", "Asia", true);
exports.flagGe = flagGe;

const flagDe = createFlag("de", "Germany", "Berlin", "Europe", true);
exports.flagDe = flagDe;

const flagGh = createFlag("gh", "Ghana", "Accra", "Africa", true);
exports.flagGh = flagGh;

const flagGi = createFlag("gi", "Gibraltar", "Gibraltar", "Europe", true);
exports.flagGi = flagGi;

const flagGr = createFlag("gr", "Greece", "Athens", "Europe", true);
exports.flagGr = flagGr;

const flagGl = createFlag("gl", "Greenland", "Nuuk", "North America", true);
exports.flagGl = flagGl;

const flagGd = createFlag(
  "gd",
  "Grenada",
  "St. George's",
  "North America",
  true,
);
exports.flagGd = flagGd;

const flagGp = createFlag(
  "gp",
  "Guadeloupe",
  "Basse-Terre",
  "North America",
  true,
);
exports.flagGp = flagGp;

const flagGu = createFlag("gu", "Guam", "Hagåtña", "Oceania", true);
exports.flagGu = flagGu;

const flagGt = createFlag(
  "gt",
  "Guatemala",
  "Guatemala City",
  "North America",
  true,
);
exports.flagGt = flagGt;

const flagGg = createFlag("gg", "Guernsey", "Saint Peter Port", "Europe", true);
exports.flagGg = flagGg;

const flagGn = createFlag("gn", "Guinea", "Conakry", "Africa", true);
exports.flagGn = flagGn;

const flagGw = createFlag("gw", "Guinea-Bissau", "Bissau", "Africa", true);
exports.flagGw = flagGw;

const flagGy = createFlag("gy", "Guyana", "Georgetown", "South America", true);
exports.flagGy = flagGy;

const flagHt = createFlag(
  "ht",
  "Haiti",
  "Port-au-Prince",
  "North America",
  true,
);
exports.flagHt = flagHt;

const flagHm = createFlag(
  "hm",
  "Heard Island and McDonald Islands",
  null,
  null,
  true,
);
exports.flagHm = flagHm;

const flagVa = createFlag("va", "Holy See", "Vatican City", "Europe", true);
exports.flagVa = flagVa;

const flagHn = createFlag(
  "hn",
  "Honduras",
  "Tegucigalpa",
  "North America",
  true,
);
exports.flagHn = flagHn;

const flagHk = createFlag("hk", "Hong Kong", "Hong Kong", "Asia", true);
exports.flagHk = flagHk;

const flagHu = createFlag("hu", "Hungary", "Budapest", "Europe", true);
exports.flagHu = flagHu;

const flagIs = createFlag("is", "Iceland", "Reykjavik", "Europe", true);
exports.flagIs = flagIs;

const flagIn = createFlag("in", "India", "New Delhi", "Asia", true);
exports.flagIn = flagIn;

const flagId = createFlag("id", "Indonesia", "Jakarta", "Asia", true);
exports.flagId = flagId;

const flagIr = createFlag("ir", "Iran", "Tehran", "Asia", true);
exports.flagIr = flagIr;

const flagIq = createFlag("iq", "Iraq", "Baghdad", "Asia", true);
exports.flagIq = flagIq;

const flagIe = createFlag("ie", "Ireland", "Dublin", "Europe", true);
exports.flagIe = flagIe;

const flagIm = createFlag("im", "Isle of Man", "Douglas", "Europe", true);
exports.flagIm = flagIm;

const flagIl = createFlag("il", "Israel", "Jerusalem", "Asia", true);
exports.flagIl = flagIl;

const flagIt = createFlag("it", "Italy", "Rome", "Europe", true);
exports.flagIt = flagIt;

const flagJm = createFlag("jm", "Jamaica", "Kingston", "North America", true);
exports.flagJm = flagJm;

const flagJp = createFlag("jp", "Japan", "Tokyo", "Asia", true);
exports.flagJp = flagJp;

const flagJe = createFlag("je", "Jersey", "Saint Helier", "Europe", true);
exports.flagJe = flagJe;

const flagJo = createFlag("jo", "Jordan", "Amman", "Asia", true);
exports.flagJo = flagJo;

const flagKz = createFlag("kz", "Kazakhstan", "Astana", "Asia", true);
exports.flagKz = flagKz;

const flagKe = createFlag("ke", "Kenya", "Nairobi", "Africa", true);
exports.flagKe = flagKe;

const flagKi = createFlag("ki", "Kiribati", "South Tarawa", "Oceania", true);
exports.flagKi = flagKi;

const flagXk = createFlag("xk", "Kosovo", "Pristina", "Europe", false);
exports.flagXk = flagXk;

const flagKw = createFlag("kw", "Kuwait", "Kuwait City", "Asia", true);
exports.flagKw = flagKw;

const flagKg = createFlag("kg", "Kyrgyzstan", "Bishkek", "Asia", true);
exports.flagKg = flagKg;

const flagLa = createFlag("la", "Laos", "Vientiane", "Asia", true);
exports.flagLa = flagLa;

const flagLv = createFlag("lv", "Latvia", "Riga", "Europe", true);
exports.flagLv = flagLv;

const flagArab = createFlag("arab", "League of Arab States", null, null, false);
exports.flagArab = flagArab;

const flagLb = createFlag("lb", "Lebanon", "Beirut", "Asia", true);
exports.flagLb = flagLb;

const flagLs = createFlag("ls", "Lesotho", "Maseru", "Africa", true);
exports.flagLs = flagLs;

const flagLr = createFlag("lr", "Liberia", "Monrovia", "Africa", true);
exports.flagLr = flagLr;

const flagLy = createFlag("ly", "Libya", "Tripoli", "Africa", true);
exports.flagLy = flagLy;

const flagLi = createFlag("li", "Liechtenstein", "Vaduz", "Europe", true);
exports.flagLi = flagLi;

const flagLt = createFlag("lt", "Lithuania", "Vilnius", "Europe", true);
exports.flagLt = flagLt;

const flagLu = createFlag(
  "lu",
  "Luxembourg",
  "Luxembourg City",
  "Europe",
  true,
);
exports.flagLu = flagLu;

const flagMo = createFlag("mo", "Macau", "Macau", "Asia", true);
exports.flagMo = flagMo;

const flagMg = createFlag("mg", "Madagascar", "Antananarivo", "Africa", true);
exports.flagMg = flagMg;

const flagMw = createFlag("mw", "Malawi", "Lilongwe", "Africa", true);
exports.flagMw = flagMw;

const flagMy = createFlag("my", "Malaysia", "Kuala Lumpur", "Asia", true);
exports.flagMy = flagMy;

const flagMv = createFlag("mv", "Maldives", "Malé", "Asia", true);
exports.flagMv = flagMv;

const flagMl = createFlag("ml", "Mali", "Bamako", "Africa", true);
exports.flagMl = flagMl;

const flagMt = createFlag("mt", "Malta", "Valletta", "Europe", true);
exports.flagMt = flagMt;

const flagMh = createFlag("mh", "Marshall Islands", "Majuro", "Oceania", true);
exports.flagMh = flagMh;

const flagMq = createFlag(
  "mq",
  "Martinique",
  "Fort-de-France",
  "North America",
  true,
);
exports.flagMq = flagMq;

const flagMr = createFlag("mr", "Mauritania", "Nouakchott", "Africa", true);
exports.flagMr = flagMr;

const flagMu = createFlag("mu", "Mauritius", "Port Louis", "Africa", true);
exports.flagMu = flagMu;

const flagYt = createFlag("yt", "Mayotte", "Mamoudzou", "Africa", true);
exports.flagYt = flagYt;

const flagMx = createFlag("mx", "Mexico", "Mexico City", "North America", true);
exports.flagMx = flagMx;

const flagMd = createFlag("md", "Moldova", "Chișinău", "Europe", true);
exports.flagMd = flagMd;

const flagMc = createFlag("mc", "Monaco", "Monaco", "Europe", true);
exports.flagMc = flagMc;

const flagMn = createFlag("mn", "Mongolia", "Ulaanbaatar", "Asia", true);
exports.flagMn = flagMn;

const flagMe = createFlag("me", "Montenegro", "Podgorica", "Europe", true);
exports.flagMe = flagMe;

const flagMs = createFlag(
  "ms",
  "Montserrat",
  "Little Bay, Brades, Plymouth",
  "North America",
  true,
);
exports.flagMs = flagMs;

const flagMa = createFlag("ma", "Morocco", "Rabat", "Africa", true);
exports.flagMa = flagMa;

const flagMz = createFlag("mz", "Mozambique", "Maputo", "Africa", true);
exports.flagMz = flagMz;

const flagMm = createFlag("mm", "Myanmar", "Naypyidaw", "Asia", true);
exports.flagMm = flagMm;

const flagNa = createFlag("na", "Namibia", "Windhoek", "Africa", true);
exports.flagNa = flagNa;

const flagNr = createFlag("nr", "Nauru", "Yaren District", "Oceania", true);
exports.flagNr = flagNr;

const flagNp = createFlag("np", "Nepal", "Kathmandu", "Asia", true);
exports.flagNp = flagNp;

const flagNl = createFlag("nl", "Netherlands", "Amsterdam", "Europe", true);
exports.flagNl = flagNl;

const flagNc = createFlag("nc", "New Caledonia", "Nouméa", "Oceania", true);
exports.flagNc = flagNc;

const flagNz = createFlag("nz", "New Zealand", "Wellington", "Oceania", true);
exports.flagNz = flagNz;

const flagNi = createFlag("ni", "Nicaragua", "Managua", "North America", true);
exports.flagNi = flagNi;

const flagNe = createFlag("ne", "Niger", "Niamey", "Africa", true);
exports.flagNe = flagNe;

const flagNg = createFlag("ng", "Nigeria", "Abuja", "Africa", true);
exports.flagNg = flagNg;

const flagNu = createFlag("nu", "Niue", "Alofi", "Oceania", true);
exports.flagNu = flagNu;

const flagNf = createFlag("nf", "Norfolk Island", "Kingston", "Oceania", true);
exports.flagNf = flagNf;

const flagKp = createFlag("kp", "North Korea", "Pyongyang", "Asia", true);
exports.flagKp = flagKp;

const flagMk = createFlag("mk", "North Macedonia", "Skopje", "Europe", true);
exports.flagMk = flagMk;

const flagGbNir = createFlag(
  "gb-nir",
  "Northern Ireland",
  "Belfast",
  "Europe",
  false,
);
exports.flagGbNir = flagGbNir;

const flagMp = createFlag(
  "mp",
  "Northern Mariana Islands",
  "Saipan",
  "Oceania",
  true,
);
exports.flagMp = flagMp;

const flagNo = createFlag("no", "Norway", "Oslo", "Europe", true);
exports.flagNo = flagNo;

const flagOm = createFlag("om", "Oman", "Muscat", "Asia", true);
exports.flagOm = flagOm;

const flagPc = createFlag("pc", "Pacific Community", null, null, false);
exports.flagPc = flagPc;

const flagPk = createFlag("pk", "Pakistan", "Islamabad", "Asia", true);
exports.flagPk = flagPk;

const flagPw = createFlag("pw", "Palau", "Ngerulmud", "Oceania", true);
exports.flagPw = flagPw;

const flagPa = createFlag("pa", "Panama", "Panama City", "North America", true);
exports.flagPa = flagPa;

const flagPg = createFlag(
  "pg",
  "Papua New Guinea",
  "Port Moresby",
  "Oceania",
  true,
);
exports.flagPg = flagPg;

const flagPy = createFlag("py", "Paraguay", "Asunción", "South America", true);
exports.flagPy = flagPy;

const flagPe = createFlag("pe", "Peru", "Lima", "South America", true);
exports.flagPe = flagPe;

const flagPh = createFlag("ph", "Philippines", "Manila", "Asia", true);
exports.flagPh = flagPh;

const flagPn = createFlag("pn", "Pitcairn", "Adamstown", "Oceania", true);
exports.flagPn = flagPn;

const flagPl = createFlag("pl", "Poland", "Warsaw", "Europe", true);
exports.flagPl = flagPl;

const flagPt = createFlag("pt", "Portugal", "Lisbon", "Europe", true);
exports.flagPt = flagPt;

const flagPr = createFlag(
  "pr",
  "Puerto Rico",
  "San Juan",
  "North America",
  true,
);
exports.flagPr = flagPr;

const flagQa = createFlag("qa", "Qatar", "Doha", "Asia", true);
exports.flagQa = flagQa;

const flagCg = createFlag(
  "cg",
  "Republic of the Congo",
  "Brazzaville",
  "Africa",
  true,
);
exports.flagCg = flagCg;

const flagRo = createFlag("ro", "Romania", "Bucharest", "Europe", true);
exports.flagRo = flagRo;

const flagRu = createFlag("ru", "Russia", "Moscow", "Europe", true);
exports.flagRu = flagRu;

const flagRw = createFlag("rw", "Rwanda", "Kigali", "Africa", true);
exports.flagRw = flagRw;

const flagRe = createFlag("re", "Réunion", "Saint-Denis", "Africa", true);
exports.flagRe = flagRe;

const flagBl = createFlag(
  "bl",
  "Saint Barthélemy",
  "Gustavia",
  "North America",
  true,
);
exports.flagBl = flagBl;

const flagShHl = createFlag(
  "sh-hl",
  "Saint Helena",
  "Jamestown",
  "Africa",
  false,
);
exports.flagShHl = flagShHl;

const flagSh = createFlag(
  "sh",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Jamestown",
  "Africa",
  true,
);
exports.flagSh = flagSh;

const flagKn = createFlag(
  "kn",
  "Saint Kitts and Nevis",
  "Basseterre",
  "North America",
  true,
);
exports.flagKn = flagKn;

const flagLc = createFlag(
  "lc",
  "Saint Lucia",
  "Castries",
  "North America",
  true,
);
exports.flagLc = flagLc;

const flagMf = createFlag(
  "mf",
  "Saint Martin",
  "Marigot",
  "North America",
  true,
);
exports.flagMf = flagMf;

const flagPm = createFlag(
  "pm",
  "Saint Pierre and Miquelon",
  "Saint-Pierre",
  "North America",
  true,
);
exports.flagPm = flagPm;

const flagVc = createFlag(
  "vc",
  "Saint Vincent and the Grenadines",
  "Kingstown",
  "North America",
  true,
);
exports.flagVc = flagVc;

const flagWs = createFlag("ws", "Samoa", "Apia", "Oceania", true);
exports.flagWs = flagWs;

const flagSm = createFlag("sm", "San Marino", "San Marino", "Europe", true);
exports.flagSm = flagSm;

const flagSt = createFlag(
  "st",
  "Sao Tome and Principe",
  "São Tomé",
  "Africa",
  true,
);
exports.flagSt = flagSt;

const flagSa = createFlag("sa", "Saudi Arabia", "Riyadh", "Asia", true);
exports.flagSa = flagSa;

const flagGbSct = createFlag(
  "gb-sct",
  "Scotland",
  "Edinburgh",
  "Europe",
  false,
);
exports.flagGbSct = flagGbSct;

const flagSn = createFlag("sn", "Senegal", "Dakar", "Africa", true);
exports.flagSn = flagSn;

const flagRs = createFlag("rs", "Serbia", "Belgrade", "Europe", true);
exports.flagRs = flagRs;

const flagSc = createFlag("sc", "Seychelles", "Victoria", "Africa", true);
exports.flagSc = flagSc;

const flagSl = createFlag("sl", "Sierra Leone", "Freetown", "Africa", true);
exports.flagSl = flagSl;

const flagSg = createFlag("sg", "Singapore", "Singapore", "Asia", true);
exports.flagSg = flagSg;

const flagSx = createFlag(
  "sx",
  "Sint Maarten",
  "Philipsburg",
  "North America",
  true,
);
exports.flagSx = flagSx;

const flagSk = createFlag("sk", "Slovakia", "Bratislava", "Europe", true);
exports.flagSk = flagSk;

const flagSi = createFlag("si", "Slovenia", "Ljubljana", "Europe", true);
exports.flagSi = flagSi;

const flagSb = createFlag("sb", "Solomon Islands", "Honiara", "Oceania", true);
exports.flagSb = flagSb;

const flagSo = createFlag("so", "Somalia", "Mogadishu", "Africa", true);
exports.flagSo = flagSo;

const flagZa = createFlag("za", "South Africa", "Pretoria", "Africa", true);
exports.flagZa = flagZa;

const flagGs = createFlag(
  "gs",
  "South Georgia and the South Sandwich Islands",
  "King Edward Point",
  "Antarctica",
  true,
);
exports.flagGs = flagGs;

const flagKr = createFlag("kr", "South Korea", "Seoul", "Asia", true);
exports.flagKr = flagKr;

const flagSs = createFlag("ss", "South Sudan", "Juba", "Africa", true);
exports.flagSs = flagSs;

const flagEs = createFlag("es", "Spain", "Madrid", "Europe", true);
exports.flagEs = flagEs;

const flagLk = createFlag(
  "lk",
  "Sri Lanka",
  "Sri Jayawardenepura Kotte, Colombo",
  "Asia",
  true,
);
exports.flagLk = flagLk;

const flagPs = createFlag("ps", "State of Palestine", "Ramallah", "Asia", true);
exports.flagPs = flagPs;

const flagSd = createFlag("sd", "Sudan", "Khartoum", "Africa", true);
exports.flagSd = flagSd;

const flagSr = createFlag(
  "sr",
  "Suriname",
  "Paramaribo",
  "South America",
  true,
);
exports.flagSr = flagSr;

const flagSj = createFlag(
  "sj",
  "Svalbard and Jan Mayen",
  "Longyearbyen",
  "Europe",
  true,
);
exports.flagSj = flagSj;

const flagSe = createFlag("se", "Sweden", "Stockholm", "Europe", true);
exports.flagSe = flagSe;

const flagCh = createFlag("ch", "Switzerland", "Bern", "Europe", true);
exports.flagCh = flagCh;

const flagSy = createFlag("sy", "Syria", "Damascus", "Asia", true);
exports.flagSy = flagSy;

const flagTw = createFlag("tw", "Taiwan", "Taipei", "Asia", true);
exports.flagTw = flagTw;

const flagTj = createFlag("tj", "Tajikistan", "Dushanbe", "Asia", true);
exports.flagTj = flagTj;

const flagTz = createFlag("tz", "Tanzania", "Dodoma", "Africa", true);
exports.flagTz = flagTz;

const flagTh = createFlag("th", "Thailand", "Bangkok", "Asia", true);
exports.flagTh = flagTh;

const flagTl = createFlag("tl", "Timor-Leste", "Dili", "Asia", true);
exports.flagTl = flagTl;

const flagTg = createFlag("tg", "Togo", "Lomé", "Africa", true);
exports.flagTg = flagTg;

const flagTk = createFlag(
  "tk",
  "Tokelau",
  "Nukunonu, Atafu,Tokelau",
  "Oceania",
  true,
);
exports.flagTk = flagTk;

const flagTo = createFlag("to", "Tonga", "Nukuʻalofa", "Oceania", true);
exports.flagTo = flagTo;

const flagTt = createFlag(
  "tt",
  "Trinidad and Tobago",
  "Port of Spain",
  "South America",
  true,
);
exports.flagTt = flagTt;

const flagShTa = createFlag(
  "sh-ta",
  "Tristan da Cunha",
  "Edinburgh of the Seven Seas",
  "Africa",
  false,
);
exports.flagShTa = flagShTa;

const flagTn = createFlag("tn", "Tunisia", "Tunis", "Africa", true);
exports.flagTn = flagTn;

const flagTm = createFlag("tm", "Turkmenistan", "Ashgabat", "Asia", true);
exports.flagTm = flagTm;

const flagTc = createFlag(
  "tc",
  "Turks and Caicos Islands",
  "Cockburn Town",
  "North America",
  true,
);
exports.flagTc = flagTc;

const flagTv = createFlag("tv", "Tuvalu", "Funafuti", "Oceania", true);
exports.flagTv = flagTv;

const flagTr = createFlag("tr", "Türkiye", "Ankara", "Asia", true);
exports.flagTr = flagTr;

const flagUg = createFlag("ug", "Uganda", "Kampala", "Africa", true);
exports.flagUg = flagUg;

const flagUa = createFlag("ua", "Ukraine", "Kiev", "Europe", true);
exports.flagUa = flagUa;

const flagAe = createFlag(
  "ae",
  "United Arab Emirates",
  "Abu Dhabi",
  "Asia",
  true,
);
exports.flagAe = flagAe;

const flagGb = createFlag("gb", "United Kingdom", "London", "Europe", true);
exports.flagGb = flagGb;

const flagUn = createFlag("un", "United Nations", null, null, false);
exports.flagUn = flagUn;

const flagUm = createFlag(
  "um",
  "United States Minor Outlying Islands",
  "Washington, D.C.",
  "North America",
  true,
);
exports.flagUm = flagUm;

const flagUs = createFlag(
  "us",
  "United States of America",
  "Washington, D.C.",
  "North America",
  true,
);
exports.flagUs = flagUs;

const flagXx = createFlag("xx", "Unknown", null, null, false);
exports.flagXx = flagXx;

const flagUy = createFlag("uy", "Uruguay", "Montevideo", "South America", true);
exports.flagUy = flagUy;

const flagUz = createFlag("uz", "Uzbekistan", "Tashkent", "Asia", true);
exports.flagUz = flagUz;

const flagVu = createFlag("vu", "Vanuatu", "Port Vila", "Oceania", true);
exports.flagVu = flagVu;

const flagVe = createFlag("ve", "Venezuela", "Caracas", "South America", true);
exports.flagVe = flagVe;

const flagVn = createFlag("vn", "Vietnam", "Hanoi", "Asia", true);
exports.flagVn = flagVn;

const flagVg = createFlag(
  "vg",
  "Virgin Islands (British)",
  "Road Town",
  "North America",
  true,
);
exports.flagVg = flagVg;

const flagVi = createFlag(
  "vi",
  "Virgin Islands (U.S.)",
  "Charlotte Amalie",
  "North America",
  true,
);
exports.flagVi = flagVi;

const flagGbWls = createFlag("gb-wls", "Wales", "Cardiff", "Europe", false);
exports.flagGbWls = flagGbWls;

const flagWf = createFlag(
  "wf",
  "Wallis and Futuna",
  "Mata-Utu",
  "Oceania",
  true,
);
exports.flagWf = flagWf;

const flagEh = createFlag("eh", "Western Sahara", "Laayoune", "Africa", true);
exports.flagEh = flagEh;

const flagYe = createFlag("ye", "Yemen", "Sana'a", "Asia", true);
exports.flagYe = flagYe;

const flagZm = createFlag("zm", "Zambia", "Lusaka", "Africa", true);
exports.flagZm = flagZm;

const flagZw = createFlag("zw", "Zimbabwe", "Harare", "Africa", true);
exports.flagZw = flagZw;
