#!/usr/bin/env python3
"""Generate JavaScript module files for flag metadata exports."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULE_DIR = ROOT / "module"
MODULE_DIR.mkdir(exist_ok=True)

COUNTRY_PATH = ROOT / "country.json"

with COUNTRY_PATH.open(encoding="utf-8") as f:
    COUNTRIES = json.load(f)


def identifier(code: str) -> str:
    parts = code.split("-")
    return "flag" + "".join(part.capitalize() for part in parts)


def bool_literal(value: bool) -> str:
    return "true" if value else "false"


def optional_literal(value: str | None) -> str:
    if value is None:
        return "null"
    return json.dumps(value, ensure_ascii=False)


def generate_esm() -> str:
    lines: list[str] = []
    lines.append("// This file is generated by scripts/generate-modules.py.")
    lines.append("// Do not edit manually.\n")
    lines.append(
        "const createFlag = (code, name, capital, continent, iso) =>\n"
        "  Object.freeze({\n"
        "    code,\n"
        "    name,\n"
        "    capital,\n"
        "    continent,\n"
        "    iso,\n"
        "    square: new URL(`../flags/1x1/${code}.svg`, import.meta.url).href,\n"
        "    rectangular: new URL(`../flags/4x3/${code}.svg`, import.meta.url).href,\n"
        "  });\n"
    )
    for country in COUNTRIES:
        export_name = identifier(country["code"])
        lines.append(
            f"export const {export_name} = createFlag("
            f"{json.dumps(country['code'], ensure_ascii=False)}, "
            f"{json.dumps(country['name'], ensure_ascii=False)}, "
            f"{optional_literal(country.get('capital'))}, "
            f"{optional_literal(country.get('continent'))}, "
            f"{bool_literal(country.get('iso', False))}" ");"
        )
    lines.append("")
    return "\n".join(lines)


def generate_cjs() -> str:
    lines: list[str] = []
    lines.append("// This file is generated by scripts/generate-modules.py.")
    lines.append("// Do not edit manually.")
    lines.append("'use strict';\n")
    lines.append("const path = require('path');\n")
    lines.append(
        "const createFlag = (code, name, capital, continent, iso) =>\n"
        "  Object.freeze({\n"
        "    code,\n"
        "    name,\n"
        "    capital,\n"
        "    continent,\n"
        "    iso,\n"
        "    square: path.join(__dirname, '..', 'flags', '1x1', `${code}.svg`),\n"
        "    rectangular: path.join(__dirname, '..', 'flags', '4x3', `${code}.svg`),\n"
        "  });\n"
    )
    for country in COUNTRIES:
        export_name = identifier(country["code"])
        lines.append(
            f"const {export_name} = createFlag("
            f"{json.dumps(country['code'], ensure_ascii=False)}, "
            f"{json.dumps(country['name'], ensure_ascii=False)}, "
            f"{optional_literal(country.get('capital'))}, "
            f"{optional_literal(country.get('continent'))}, "
            f"{bool_literal(country.get('iso', False))}" ");"
        )
        lines.append(f"exports.{export_name} = {export_name};\n")
    return "\n".join(lines)


def generate_d_ts() -> str:
    lines: list[str] = []
    lines.append("// This file is generated by scripts/generate-modules.py.")
    lines.append("// Do not edit manually.\n")
    lines.append("export interface FlagIconDefinition {\n"
                 "  code: FlagIconCode;\n"
                 "  name: string;\n"
                 "  capital: string | null;\n"
                 "  continent: string | null;\n"
                 "  iso: boolean;\n"
                 "  square: string;\n"
                 "  rectangular: string;\n"
                 "}\n")
    lines.append("export type FlagIconCode =")
    for country in COUNTRIES:
        lines.append(f"  | {json.dumps(country['code'], ensure_ascii=False)}")
    lines[-1] += ';\n'
    lines.append("export type FlagIcon = FlagIconDefinition;\n")
    for country in COUNTRIES:
        export_name = identifier(country["code"])
        lines.append(f"export declare const {export_name}: FlagIconDefinition;")
    lines.append("")
    return "\n".join(lines)


(MODULE_DIR / "index.mjs").write_text(generate_esm(), encoding="utf-8")
(MODULE_DIR / "index.cjs").write_text(generate_cjs(), encoding="utf-8")
(MODULE_DIR / "index.d.ts").write_text(generate_d_ts(), encoding="utf-8")
